{% set name = "dialectid" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dialectid-{{ version }}.tar.gz
  sha256: 6fc4ef2519339b3823925f436511a90bf34458b3a379449fb950a202fcc8857f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - scikit-learn
    - microtc
    - b4msa
    - encexp

test:
  imports:
    - dialectid
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/dialectid/
  summary: Computational models for dialect identification.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
