{% set name = "dialectid" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dialectid-{{ version }}.tar.gz
  sha256: 48ad4b5b4717aaedbe0a9bc064d9232d29e98e4d0b6288008fdf0b8a1592855a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - scikit-learn
  run:
    - python >=3.6
    - scikit-learn
    - microtc
    - b4msa
    - evomsa

test:
  imports:
    - dialectid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/dialectid/
  summary: Computational models for dialect identification.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
