{% set name = "dialectid" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dialectid-{{ version }}.tar.gz
  sha256: 653da5cf08e5f5dd4ad8b57971254d59b76c59bfbc02826ae376ab202b9acfa7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - scikit-learn
  run:
    - python >={{ python_min }}
    - scikit-learn
    - microtc
    - b4msa
    - evomsa

test:
  imports:
    - dialectid
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/dialectid/
  summary: Computational models for dialect identification.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mgraffg
